services:
  db:
    image: mysql:latest
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app_network

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/go/src/
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/openapi
    ports:
      - "8010:8080"

  prism:
    image: stoplight/prism:4
    command: "mock -h 0.0.0.0 /openapi/openapi.yaml"
    volumes:
      - ./openapi:/openapi
    ports:
      - "8011:4010"

volumes:
  mysql_data:

networks:
  app_network:
