openapi: 3.1.0
info:
  title: bibliotheca API
  description: bibliotheca関連API
  version: 1.0.0

paths:
  /users:
    $ref: "./paths/index.yaml#/users"
  /users/{id}:
    $ref: "./paths/index.yaml#/users_id"
